# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d35724573a05a865ac67cc6dec83899f83f8fc081d8cba27a4b911f4693dc82305179aad8f1932f6872ebfd1955e31e0e28221b78889d964b301d9fcd37bc39

test:
  secret_key_base: 7a98cc4af3c174abda66cace12267e98cc67ac440bb973cd9dcd96148fc68c73076474ddbb082d19407a55256a87f4e8896b3357f5ab45bce1936b87fc8d8cc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
